# Site settings
title: Moodule
subtitle: I write code to solve problems
description: >- # this means to ignore newlines until "baseurl:"
  "To solve real problems: getting out of bed!
  Assisting the design of industrial processes or streamlining a digital workflow."
logo: /assets/images/logo.svg

# Contact informations
email: apehex@protonmail.com

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/moodule
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Collections
collections:
  projects:
    output: false

# Layouts
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex

# Exclude from processing
