# Site settings
title: Moodule
email: apehex@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "I write code to solve problems.
  Real problems: getting out of bed!
  Assisting the design of industrial processes or streamlining a digital workflow."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: moodule
github_username:  moodule

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: false

# Layouts
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
