# Site settings
title: Open Sourcerer / Vagabond Coder
description: >- # this means to ignore newlines until "baseurl:"
  I'm a vagabond tinkerer, doing my best to give back to Open Source. 
  I have a kink for tensors, I love functional programming and processing signals for hidden meaning.
  I spend what's left of my time in remote places, they bring me back to the present to feel and think my way, literally.

# Contact information
street_address:
city: Lyon
state: Rhône Alpes
zip_code: 69005
country: France
phone:
email: moodule@protonmail.com

# Social settings
github:
  url: https://github.com/moodule
  label: "@moodule"
gitlab:
  url:
  label:
instagram:
  url:
  label:
medium:
  url:
  label:

# Optional elements
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Recaptcha in forms
recaptcha:
  sitekey: 6LfMnsgUAAAAAHVZt3lPn_Y5siUXGOBaTQ3cRoZ0

# Collections
collections_dir: panels
collections:
  about:
    output: false
  drafts:
    output: false
  home:
    output: false
  homespace:
    output: false
  posts:
    output: false
  projects:
    output: false

# Default settings
defaults:
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
theme: jekyll-theme-ethereal
permalink: /:categories/:title/
markdown: kramdown
sass:
  sourcemap: never
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moodule.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex
copyright:
  holder: Moodule
  license: MIT license

# Exclude from processing
